var DEFAULTS = {
	"processingEnabled": true,
	"autoMode": true,
	"idleTime": "1", 
	"website1": "http://news.google.com",
	"website2": "http://www.yahoo.com",
	"website3": "http://www.cnet.com",
	"website4": "http://www.drudgereport.com",
	"website5": "http://www.msn.com",
	"website6": "http://www.wired.com",
	"website7": "",
	"website8": "",
	"website9": "",
	"website10": "",
	"minTimeBetweenClicks": 6,
	"maxTimeBetweenClicks": 20,
	"removeTabWhenFinished": false,
	"languageDetectionEnabled": true,
	"preferredLanguage": "en",
	"searchPhraseMinPercent": 20,
	"searchPhraseMaxPercent": 70,
	"browsingTimeoutMin": 30,
	"browsingTimeoutMax": 60,
	"minSiteDepth": 5,
	"maxSiteDepth": 10,
	"maxDepth": 20
};
